### ISSUE TITLE
Unable to find smithy prelude 

### ISSUE THREAD

**Issue by guillaumebadin** [iancaffey/smithy-intellij-plugin#14]
I installa smithy on my sbt scala 3 project but I have some errors. 

![Capture d’écran 2024-02-26 à 15 50 15](https://github.com/iancaffey/smithy-intellij-plugin/assets/204574/d83db741-0279-4f2e-9b42-f490dbeee4be)

**Comment by iancaffey** [comment]
Could you share your build.sbt?

As long as https://mvnrepository.com/artifact/software.amazon.smithy/smithy-model winds up getting added as a dependency (or the CLI which bundles this) for your project in IntelliJ, the plugin will be able to find the prelude.

**Comment by amacmillanparks** [comment]
I was having the same issue. Including the following dependencies:
`"software.amazon.smithy" % "smithy-model" % "1.45.0"
"com.disneystreaming.alloy" % "alloy-core" % "0.3.1"`

in my built.sbt got with working for me with sbt 1.9.9 and smithy4s 0.18.10

**Comment by iancaffey** [comment]
@guillaumebadin let me know if there's anything else I could help you with.
