### ISSUE TITLE
enum Shape is not supported

### ISSUE THREAD

**Issue by resnus** [iancaffey/smithy-intellij-plugin#7]
https://smithy.io/2.0/spec/simple-types.html#enum

Example enum:
```
enum Status {
    READY = "ready"
    ACTIVE = "active"
    COMPLETE = "complete"
}
```
Error: `'@', TOKEN_SIMPLE_TYPE_NAME, list, map, operation, resource, service, set, structure or union expected, got 'enum'`

**Comment by iancaffey** [comment]
Which version of the plugin are you using?

2.0 IDL features were added in the 2.0.0 release of the plugin.

**Comment by resnus** [comment]
You are right, I was getting `1.03` version by default. I have upgraded Intellij to the latest revision and installed the latest version of the plugin. This has resolved the issue. Thank you.
Sorry for a false report and thank you for quick response!

**Comment by iancaffey** [comment]
No worries! Glad it fixed the issue and hope you enjoy all the new features.
