### ISSUE TITLE
Traits not correctly highlighted 

### ISSUE THREAD

**Issue by DiegoMC9** [iancaffey/smithy-intellij-plugin#8]
* Intellij-Version: IntelliJ IDEA 2023.1.1 (Ultimate Edition)
* Using New UI
* Smithy Plugin Version: 2.0.8

Observed behaviour: 
* Traits get identified as shapes, reporting "Unresolved shape <trait>"
* Similar behaviour happens with *use* statements, reporting "Unresolved shape <package>" error on the use statement and its usage

![Screenshot 2023-05-12 at 5 03 09 PM](https://github.com/iancaffey/smithy-intellij-plugin/assets/12599835/d40e2119-e7ef-4bf8-abb0-2439aeaccc23)

**Comment by iancaffey** [comment]
What are you using to build your smithy models? The CLI or the Gradle plugin. 

> Traits get identified as shapes, reporting "Unresolved shape "

Traits _are_ shapes, or just can't find smithy.api#title. 

What you're observing there is from dependencies not being configured properly in IntelliJ. 

If you're using the CLI, dependency jars (and the CLI itself or the smithy-model package for prelude shapes) which contain smithy shapes that you depend on have to be manually added as dependencies to your IntelliJ project for the time being until the build system integration is added. 

If you're using Gradle, there's nothing special required. The built in gradle support handles smithy dependencies out of the box.

**Comment by iancaffey** [comment]
Hey Diego, let me know if there's anything else I can help with. 

Going to resolve the issue for now.

**Comment by DiegoMC9** [comment]
Thank you, i'll double check the build system!
